version: '3.8'

services:
  kong:
    image: kong:latest
    restart: always
    networks:
      - db-network
    environment:
      KONG_DATABASE: off
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled,cors
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    volumes:
      - ./api-gateway/kong.yml:/usr/local/kong/declarative/kong.yml

  mysql-db:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "4000:3306"
    networks:
      - db-network
    volumes:
      - mysql_data:/var/lib/mysql

  law-service:
    build: ./law-service
    restart: always
    depends_on:
      - mysql-db
    networks:
      - db-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:4000/law_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "9002:9002"

  auth-service:
    build: ./auth-service
    restart: always
    depends_on:
      - mysql-db
    networks:
      - db-network
    env_file:
      - ./auth-service/src/main/resources/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/auth_service
    ports:
      - "9001:9001"

  react-frontend:
    build:
      context: ./front-end/website
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - db-network
    depends_on:
      - kong
    expose:
      - "5173"
      - "3000"
    volumes:
      - ./front-end/website:/app
      - /app/node_modules
    env_file:
      - ./front-end/website/.env
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME=localhost
    ports:
      - "9090:8080"
    depends_on:
      - keycloak-db
    command: start-dev

  keycloak-db:
      image: postgres:14
      container_name: keycloak-db
      environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=keycloak
      volumes:
        - keycloak-db-data:/var/lib/postgresql/data

volumes:
  mysql_data:
  keycloak-db-data:

networks:
  db-network:
    driver: bridge