version: '3.8'

services:
  kong:
    image: kong:latest
    restart: always
    networks:
      - db-network
    environment:
      KONG_DATABASE: off
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled,cors
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    volumes:
      - ./api-gateway/kong.yml:/usr/local/kong/declarative/kong.yml

  mysql-db:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth_service  # Tạo sẵn database auth_service
      MYSQL_USER: auth_user         # Tạo user cho auth-service
      MYSQL_PASSWORD: auth_password # Mật khẩu cho user
    ports:
      - "3306:3306"
    networks:
      - db-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./auth-service
    restart: always
    depends_on:
      mysql-db:
        condition: service_healthy  # Chờ MySQL sẵn sàng
    networks:
      - db-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/auth_service?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  # Tự động tạo bảng nếu cần
    ports:
      - "9001:9001"
    volumes:
      - ./auth-service/src:/app/src

  react-frontend:
    build:
      context: ./front-end/website
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - db-network
    depends_on:
      - kong
    expose:
      - "5173"
    volumes:
      - ./front-end/website:/app
      - /app/node_modules
    env_file:
      - ./front-end/website/.env

volumes:
  mysql_data:

networks:
  db-network:
    driver: bridge