version: '3.8'

services:
  mysql-db:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - db-network
    volumes:
      - mysql_data:/var/lib/mysql

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    restart: always
    ports:
      - "3307:8000"  # ChromaDB Port
    networks:
      - db-network
    volumes:
      - chroma_data:/chroma/chroma
volumes:
  mysql_data:
  chroma_data:
networks:
  db-network:
    driver: bridge