version: '3.8'

services:
  mysql-db:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - db-network
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  chroma_data:
networks:
  db-network:
    driver: bridge