server:
  port: 9000

eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    io.netty: DEBUG
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
              allowedHeaders: '*'
              maxAge: 30
        - id: law-service
          uri: http://localhost:9002
          predicates:
            - Path=/law-service/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
              allowedHeaders: '*'
              maxAge: 30
        - id: chat-service
          uri: http://localhost:9003
          predicates:
            - Path=/chat-service/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
              allowedHeaders: '*'
              maxAge: 30
        - id: socket-service
          uri: http://localhost:9004
          predicates:
              - Path=/socket-service/**
          filters:
            - StripPrefix=1
          metadata:
            cors:
              allowedOrigins: 'http://localhost:3000'
              allowedMethods:
                - GET
                - POST
              allowedHeaders: '*'
              maxAge: 30
        - id: recommend-service
          uri: lb://recommend-service
          predicates:
            - Path=/recommend-service/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
              allowedHeaders: '*'
              maxAge: 30
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
