server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/auth/**
        - id: law-service
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/law/**
        - id: chat-service
          uri: http://localhost:9003
          predicates:
            - Path=/api/v1/chat/**
        - id: recommend-service
          uri: http://localhost:9004
          predicates:
            - Path=/api/v1/recommend/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"