server:
  port: 9000

eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

zuul:
  sensitive-headers:
    - Cookie, Authorization

logging:
  level:
    io.netty: DEBUG
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9001
          predicates:
            - Path=/auth-service/**
          metadata:
            cors:
              enabled: true
              allowedHeaders: "*"
              allowedMethods: "*"
              allowedOrigins: "*"

        - id: law-service
          uri: http://localhost:9002
          predicates:
            - Path=/law-service/**
          metadata:
            cors:
              enabled: true
              allowedHeaders: "*"
              allowedMethods: "*"
              allowedOrigins: "*"
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chat-service/**
        - id: recommend-service
          uri: lb://recommend-service
          predicates:
            - Path=/recommend-service/**
      default-filters:
        - name: DedupeResponseHeader
          args:
            name: Access-Control-Allow-Origin
            value: "*"
        - name: DedupeResponseHeader
          args:
            name: Access-Control-Allow-Methods
            value: "GET, POST, PUT, DELETE, HEAD, OPTIONS"
        - name: DedupeResponseHeader
          args:
            name: Access-Control-Allow-Headers
            value: "*"
        - name: DedupeResponseHeader
          args:
            name: Access-Control-Max-Age
            value: "3600"
  main:
    web-application-type: reactive
