server:
  port: 9000

eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
        - id: law-service
          uri: lb://law-service
          predicates:
            - Path=/law-service/**
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chat-service/**
        - id: recommend-service
          uri: lb://recommend-service
          predicates:
            - Path=/recommend-service/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin