[tool.poetry]
name = "crawler"
version = "0.1.0"
description = ""
authors = ["Huynguyen <nguyenmaibaohuy2003@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

