global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'your_email@gmail.com'
  smtp_auth_username: 'your_email@gmail.com'
  smtp_auth_password: 'your_app_password'

route:
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'recipient_email@example.com'