global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['192.168.1.4:9094']

rule_files:
  - 'alert_rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.1.4:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['192.168.1.4:7071']

#  - job_name: 'auth-service'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['localhost:9001']
#
#  - job_name: 'law-service'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['localhost:9002']
#
#  - job_name: 'chat-service'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['localhost:9003']