server {
    listen 80;
    server_name react-app;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # Hỗ trợ WebSocket
        location /socket-service/ws {
            proxy_pass http://api-gateway:9000/socket-service/ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

    error_page 404 /index.html;
}
