package avg.vnlaw.authservice.enums;

public enum AuthenticationResponseEnum {
    OK,
    EMAIL_ALREADY_REGISTERED,
    ACCOUNT_NOT_ACTIVATED,
    ACCOUNT_OR_PASSWORD_INCORRECT,
    ACCOUNT_LOCKED,
    ACCOUNT_EXPIRED,
    ACCOUNT_DISABLED,
    INVALID_TOKEN,
    INTERNAL_SERVER_ERROR,
    KEYCLOAK_ERROR,
    INVALID_CREDENTIALS
}
